version: "3.9"
services:
  haproxy:
    image: haproxy:alpine
    ports: [ "3000:80", "3001:81", "4001:4001" ]
    command: [
      "haproxy",
      "--",
      "/usr/local/etc/haproxy/cfg",
      "/usr/local/etc/haproxy/sites"
      ]
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  webserver:
    image: nginx:alpine
